# В этом файле будут находится решения задач по основам алгоритмики 2 семестра.
***

## Задание 1
Написать функцию `sortkey(key_values, a)`, получающую на вход некоторый вектор `a`, и соответствующий вектор `keyvalues` ключевых значений элементов вектора `a`, осуществляющую сортировку вектора `a` по ключевым значениям его элементов, и возвращающую ссылку на вектор `a`. (Для сортировки вектора ключевых значений можно востпользоваться одной из разработанных в пункте 1 функций, или соответствующей встроенной функцией).

In [1]:
function sortkey!(key_values, a)
    size = length(key_values)
    for i in 1:size
        for j in 1:size
            if key_values[i] < key_values[j]
                key_values[i], key_values[j] = key_values[j], key_values[i]
                a[i], a[j] = a[j], a[i]
            end
        end
    end
    return a
end

sortkey! (generic function with 1 method)

In [2]:
massive = [1 5 7]
keys_ = [3 2 1]
sortkey!(keys_, massive)

1×3 Array{Int64,2}:
 7  5  1

Проверим, что `massive` действительно изменился:

In [3]:
massive

1×3 Array{Int64,2}:
 7  5  1

## Задание 2
С использованием разработанной функции `sortkey` написать функцию высшего порядка, с тем же именем `sortkey`, но вместо массива ключевых значений получающую на вход ключевую функцию и массив элементов некоторого типа, на множестве значений которых должна быть определена данная ключевая функция.

In [4]:
function sortkey!(func::Function, a)
    sortkey!(func.(a), a)
end

sortkey! (generic function with 2 methods)

In [5]:
massive = [1 5 7]
function func_(a)  
    return a != 5
end
sortkey!(func_, massive)

1×3 Array{Int64,2}:
 5  1  7

Проверим, что massive действительно изменился:

In [6]:
massive

1×3 Array{Int64,2}:
 5  1  7

## Задание 3
С использованием этой последней функции отсортировать столбцы какой-либо заданной числовой матрицы в порядке
1. не убывания их сумм
2. не убывания числа нулей в них

Сначала введём вспомогательные функции: неубывание сумм и неубывание нулей

In [7]:
function non_decreasing_amounts(a)
    return sum(a)
end

function non_decreasing_zeroz(a)
    return count(i->(i==0), a)
end

non_decreasing_zeroz (generic function with 1 method)

Требуемые функции сортировки:

In [8]:
function sort1!(matrix)
    vec_colons = [@view matrix[:,j] for j in 1:size(matrix,2)]
    vec_colons = sortkey!(non_decreasing_amounts, vec_colons)
    matrix = hcat(hcat(vec_colons...))
    return matrix
end

function sort2!(matrix)
    vec_colons = [@view matrix[:,j] for j in 1:size(matrix,2)]
    vec_colons = sortkey!(non_decreasing_zeroz, vec_colons)
    matrix = hcat(hcat(vec_colons...))
    return matrix
end

sort2! (generic function with 1 method)

In [9]:
massive = [
    1 3 5 
    0 9 4 
    2 102 10 
]
sort1!(massive)

3×3 Array{Int64,2}:
 1   5    3
 0   4    9
 2  10  102

In [10]:
massive2 = [
    0 11 0 
    0 10 5
    0 0 1
]
sort2!(massive2)

3×3 Array{Int64,2}:
 11  0  0
 10  5  0
  0  1  0

Стоит отметить, что исходные массивы при этом не изменились:

In [11]:
massive

3×3 Array{Int64,2}:
 1    3   5
 0    9   4
 2  102  10

In [12]:
massive2

3×3 Array{Int64,2}:
 0  11  0
 0  10  5
 0   0  1

## Задание 4
Написать функцию `calcsort`, реализующую сортировку методом подсчета числа значений. Рассмотреть 2 варианта функции (2 её метода - в терминологии Julia): в первом варианте возможные значения элементов сортируемого массива задаются некоторым диапазоном, во втором - некоторым отсортированным массивом (вектором).

In [13]:
"""
Реализация для диапозона из 2 чисел
"""
function calcsort(a, diap::NTuple{2, Int})
    left_border, right_border = diap
    nums_count = right_border - left_border + 1
    nums = zeros(Int, nums_count)
    for i in a
        nums[i - left_border + 1] += 1 
    end
    my_ans = []
    for i in 1:(right_border - left_border + 1)
        for j in 1:nums[i]
            push!(my_ans, i + left_border - 1)
        end
    end
    return my_ans 
end

"""
Реализация для вектора значений
Хотя в общем-то вектор значений здесь никак не используется
"""
function calcsort(a, diap::Vector{Int})
    nums = Dict{Int64, Int64}()
    for i in a
        nums[i]= get(nums, i, 0) + 1
    end
    my_ans = []
    for i in sort(collect(keys(nums)))
        to_push = [i for j in 1:nums[i]]
        push!(my_ans, to_push...)
    end
    return my_ans 
end

calcsort

Проверим для интервала:

In [14]:
massive = [3, 5, 5, 3, 4]
vals = (3,5)
calcsort(massive, vals) 

5-element Array{Any,1}:
 3
 3
 4
 5
 5

Проверим для вектора значений:

In [15]:
massive = [5, 5, 5, 2, 1]
vals = [1, 2, 5]
calcsort(massive, vals) 

5-element Array{Any,1}:
 1
 2
 5
 5
 5

## Задание 5
Применить эту разработанную функцию для сортировки столбцов матрицы по числу находящихся в них нулей.

### Не представляю, как это можно сделать с моей реализацией calcsort

## Задание 6
Написать функции `insertsort!`, `insertsort`, `insertsortperm`, `insertsortperm!` (по аналогии с пунктом 1) реализующие алгоритм сортировки вставками

In [16]:
function insertsort!(a)
    n = length(a)
    for i in 2:n
        j = i - 1
        while j > 0 && a[j] > a[j + 1]
            a[j+1], a[j] = a[j], a[j+1]
            j -= 1
        end 
    end
    return a    
end

insertsort(a) = insertsort!(copy(a))

insertsort (generic function with 1 method)

Проверим, что функция работает верно:

In [17]:
massive = [1 5 3 4]
insertsort!(massive)

1×4 Array{Int64,2}:
 1  3  4  5

In [18]:
function insertsortperm!(a)
    n = length(a)
    b = []
    for i in 1:n
        push!(b, i)
    end
    for i in 2:n
        j = i - 1
        while j > 0 && a[j] > a[j + 1]
            a[j+1], a[j] = a[j], a[j+1]
            b[j+1], b[j] = b[j], b[j + 1]
            j -= 1
        end 
    end

    return b
end

insertsortperm(a) = insertsortperm!(copy(a))

insertsortperm (generic function with 1 method)

Проверим, что функция работает верно:

In [19]:
massive = [1 5 3 4]
insertsortperm!(massive)

4-element Array{Any,1}:
 1
 3
 4
 2

In [20]:
massive

1×4 Array{Int64,2}:
 1  3  4  5

## Задание 7
Дополнить функцию `insertsort!` процедурой "быстрого поиска".

Вспомогалтельная функция быстрого поиска

In [21]:
function quicksearch(iter,val)
    left = 1
    right = length(iter)
    while left < right && val != iter[div(left + right, 2)]
        if val > iter[left]
            left = left+1
        end
        if val < iter[right]
            right = right-1
        end
    end
    midl = div(left + right, 2)
    if val != iter[midl]
        if val < iter[midl]
            midl = midl-1
        elseif val>iter[midl]
            midl=midl+1
        end
    end
    return midl
end

quicksearch (generic function with 1 method)

In [22]:
function insertsort!(a)
    for k in 2:length(a)
        ind = quicksearch(a[1:k-1], a[k])
        if ind == 0
            ind = 1
        end
        insert!(a, ind, a[k])
        deleteat!(a, k+1)
    end
    return a
end

insertsort! (generic function with 1 method)

Проверим, что функция работает верно:

In [23]:
massive = [1, 5, 3, 4]
insertsort!(massive)

4-element Array{Int64,1}:
 1
 3
 4
 5